modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="frost_and_dicers_vanillaenhanced"
version="1.0.0"
displayName="frost and dicer's vanillaenhanced"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joshu, MCreator"

[[dependencies.frost_and_dicers_vanillaenhanced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



